import sys
moves = [
"Click on the orange square and then click on the red wide rectangle.",
"Click on the red square and then click on the pink square.",
"Click on the green square.",
"Click on the pink wide rectangle and then click on the pink square.",
"Do not click on anything for at least 10 seconds.",
"Click on the red wide rectangle 12 times.",
"Do not click on anything for at least 7 seconds.",
"Click on the red square 14 times.",
"Click on the background.",
"Do not click on anything for at least 9 seconds.",
"Click on the red square and then click on the orange square.",
"Click on the orange square and then click on the red wide rectangle.",
"Click on the green wide rectangle and then click on the orange wide rectangle.",
"Click on the orange wide rectangle 12 times.",
"Click on the background.",
"Click on the yellow wide rectangle and then click on the blue square.",
"Do not click on anything for at least 6 seconds.",
"Do not click on anything for at least 5 seconds.",
"Click on the yellow wide rectangle and then click on the yellow square.",
"Click on the background.",
"Click on the pink square and then click on the pink wide rectangle.",
"Click on the red wide rectangle 14 times.",
"Click on the red wide rectangle 18 times.",
"Click on the yellow square.",
"Click on the red wide rectangle 18 times.",
"Do not click on anything for at least 10 seconds.",
"Click on the yellow square.",
"Click on the background.",
"Do not click on anything for at least 9 seconds.",
"Click on the background.",
"Click on the red square and then click on the blue square.",
"Click on the blue wide rectangle and then click on the blue square.",
"Click on the green square 11 times.",
"Click on the background.",
"Click on the orange square and then click on the yellow square.",
"Click on the green square.",
"Click on the red square.",
"Click on the blue square.",
"Do not click on anything for at least 7 seconds.",
"Click on the background.",
"Click on the red wide rectangle 16 times.",
"Click on the red square.",
"Click on the pink wide rectangle 13 times.",
"Click on the orange wide rectangle 12 times.",
"Click on the green square.",
"Click on the red square.",
"Do not click on anything for at least 6 seconds.",
"Click on the red wide rectangle 16 times.",
"Click on the background.",
"Click on the red square 15 times.",
"Do not click on anything for at least 10 seconds.",
"Do not click on anything for at least 7 seconds.",
"Click on the orange wide rectangle and then click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the background.",
"Click on the pink square 16 times.",
"Click on the background.",
"Click on the yellow wide rectangle.",
"Click on the background.",
"Do not click on anything for at least 5 seconds.",
"Click on the yellow wide rectangle and then click on the blue square.",
"Click on the green square.",
"Do not click on anything for at least 7 seconds.",
"Click on the red wide rectangle and then click on the blue wide rectangle.",
"Click on the pink wide rectangle 12 times.",
"Click on the background.",
"Click on the yellow square.",
"Do not click on anything for at least 5 seconds.",
"Click on the background.",
"Click on the blue wide rectangle 16 times.",
"Do not click on anything for at least 9 seconds.",
"Do not click on anything for at least 7 seconds.",
"Click on the background.",
"Click on the blue wide rectangle 11 times.",
"Click on the red wide rectangle 13 times.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle 13 times.",
"Click on the orange wide rectangle and then click on the pink wide rectangle.",
"Click on the background.",
"Click on the orange wide rectangle and then click on the yellow wide rectangle.",
"Click on the pink square 18 times.",
"Click on the blue wide rectangle and then click on the green square.",
"Do not click on anything for at least 5 seconds.",
"Click on the red wide rectangle 16 times.",
"Click on the yellow square 13 times.",
"Click on the pink square 15 times.",
"Click on the red wide rectangle 15 times.",
"Click on the red square and then click on the green wide rectangle.",
"Click on the orange wide rectangle 20 times.",
"Do not click on anything for at least 8 seconds.",
"Click on the background.",
"Do not click on anything for at least 8 seconds.",
"Click on the background.",
"Click on the red square and then click on the green wide rectangle.",
"Click on the red square.",
"Do not click on anything for at least 6 seconds.",
"Click on the green wide rectangle.",
"Click on the green square.",
"Click on the orange square.",
"Click on the blue wide rectangle and then click on the green wide rectangle.",
"Click on the background.",
"Do not click on anything for at least 5 seconds.",
"Click on the background.",
"Do not click on anything for at least 10 seconds.",
"Click on the green wide rectangle.",
"Click on the pink square 14 times.",
"Click on the orange square 15 times.",
"Do not click on anything for at least 10 seconds.",
"Click on the orange wide rectangle and then click on the green square.",
"Click on the background.",
"Do not click on anything for at least 8 seconds.",
"Click on the pink square.",
"Click on the orange square 10 times.",
"Click on the background.",
"Click on the blue square.",
"Click on the background.",
"Do not click on anything for at least 9 seconds.",
"Click on the background.",
"Click on the green wide rectangle and then click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Do not click on anything for at least 6 seconds.",
"Click on the background.",
"Click on the orange wide rectangle.",
"Click on the background.",
"Do not click on anything for at least 9 seconds.",
"Click on the red square.",
"Do not click on anything for at least 6 seconds.",
"Click on the red square 15 times.",
"Click on the background.",
"Click on the green square.",
"Click on the orange square and then click on the pink wide rectangle.",
"Click on the green wide rectangle and then click on the blue wide rectangle.",
"Click on the green square and then click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the orange wide rectangle 18 times.",
"Click on the background.",
"Click on the pink square 16 times.",
"Click on the background.",
"Click on the red wide rectangle and then click on the pink square.",
"Do not click on anything for at least 9 seconds.",
"Click on the background.",
"Click on the pink wide rectangle.",
"Click on the pink square 16 times.",
"Click on the orange square.",
"Click on the background.",
"Click on the pink wide rectangle.",
"Click on the background.",
"Click on the blue wide rectangle 15 times.",
"Click on the red wide rectangle 17 times.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Do not click on anything for at least 10 seconds.",
"Click on the background.",
"Click on the blue wide rectangle.",
"Click on the yellow square 17 times.",
"Click on the red square 13 times.",
"Click on the blue square.",
"Click on the green square 20 times.",
"Click on the background.",
"Click on the yellow square 17 times.",
"Do not click on anything for at least 7 seconds.",
"Do not click on anything for at least 9 seconds.",
"Click on the red square 16 times.",
"Click on the background.",
"Do not click on anything for at least 6 seconds.",
"Click on the red square.",
"Click on the pink square.",
"Do not click on anything for at least 7 seconds.",
"Click on the orange wide rectangle 20 times.",
"Click on the background.",
"Do not click on anything for at least 10 seconds.",
"Click on the red square 15 times.",
"Click on the green square.",
"Click on the pink square and then click on the yellow wide rectangle.",
"Click on the green square and then click on the red wide rectangle.",
"Click on the red wide rectangle.",
"Do not click on anything for at least 7 seconds.",
"Click on the yellow square 20 times.",
"Click on the background.",
"Do not click on anything for at least 6 seconds.",
"Click on the red wide rectangle 19 times.",
"Click on the yellow square.",
"Click on the blue square.",
"Click on the red wide rectangle 16 times.",
"Click on the red wide rectangle.",
"Click on the orange wide rectangle.",
"Do not click on anything for at least 5 seconds.",
"Click on the blue wide rectangle and then click on the green wide rectangle.",
"Click on the orange square and then click on the orange wide rectangle.",
"Click on the blue wide rectangle and then click on the red square.",
"Click on the pink square 18 times.",
"Click on the green square and then click on the orange wide rectangle.",
"Click on the orange square 11 times.",
"Click on the blue square and then click on the red square.",
"Do not click on anything for at least 9 seconds.",
"Click on the pink wide rectangle 11 times.",
"Click on the red square and then click on the pink square.",
"Click on the background.",
"Do not click on anything for at least 5 seconds.",
"Click on the background.",
"Click on the green wide rectangle and then click on the pink wide rectangle.",
"Click on the yellow wide rectangle and then click on the green square.",
"Click on the blue square.",
"Click on the background.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle 19 times.",
"Do not click on anything for at least 10 seconds.",
"Click on the background.",
"Do not click on anything for at least 5 seconds.",
"Click on the background.",
"Do not click on anything for at least 8 seconds.",
"Click on the background.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the pink square and then click on the yellow wide rectangle.",
"Do not click on anything for at least 9 seconds.",
"Click on the background.",
"Do not click on anything for at least 10 seconds.",
"Do not click on anything for at least 6 seconds.",
"Do not click on anything for at least 9 seconds.",
"Click on the pink square 14 times.",
"Click on the yellow square and then click on the orange wide rectangle.",
"Click on the yellow wide rectangle and then click on the red square.",
"Click on the background.",
"Click on the pink square and then click on the green square.",
"Click on the green wide rectangle 16 times.",
"Click on the green wide rectangle and then click on the orange wide rectangle.",
"Click on the background.",
"Do not click on anything for at least 5 seconds.",
"Click on the green square and then click on the orange wide rectangle.",
"Click on the background.",
"Do not click on anything for at least 9 seconds.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle and then click on the blue square.",
"Click on the blue wide rectangle 11 times.",
"Click on the pink wide rectangle 17 times.",
"Click on the blue wide rectangle and then click on the red wide rectangle.",
"Click on the pink wide rectangle 13 times.",
"Click on the pink wide rectangle 16 times.",
"Click on the orange wide rectangle and then click on the yellow wide rectangle.",
"Click on the yellow square 18 times.",
"Do not click on anything for at least 9 seconds.",
"Click on the red square and then click on the pink wide rectangle.",
"Click on the blue square 16 times.",
"Click on the background.",
"Click on the blue square 18 times.",
"Click on the background.",
"Do not click on anything for at least 8 seconds.",
"Do not click on anything for at least 6 seconds.",
"Click on the blue wide rectangle.",
"Do not click on anything for at least 9 seconds.",
"Click on the background.",
"Click on the green wide rectangle and then click on the orange wide rectangle.",
"Click on the green wide rectangle and then click on the blue square.",
"Click on the green wide rectangle and then click on the blue wide rectangle.",
"Click on the red square and then click on the pink wide rectangle.",
"Click on the pink square and then click on the pink wide rectangle.",
"Click on the green square and then click on the green wide rectangle.",
"Click on the orange wide rectangle 13 times.",
"Click on the blue square.",
"Click on the background.",
"Click on the pink wide rectangle and then click on the blue square.",
"Click on the background.",
"Do not click on anything for at least 7 seconds.",
"Click on the yellow wide rectangle.",
"Do not click on anything for at least 5 seconds.",
"Do not click on anything for at least 10 seconds.",
"Click on the yellow wide rectangle 10 times.",
"Click on the background.",
"Click on the blue square 10 times.",
"Click on the yellow square 14 times.",
"Click on the blue wide rectangle.",
"Do not click on anything for at least 9 seconds.",
"Click on the background.",
"Do not click on anything for at least 7 seconds.",
"Do not click on anything for at least 10 seconds.",
"Click on the background.",
"Click on the yellow square 18 times.",
"Click on the background.",
"Click on the green wide rectangle and then click on the red square.",
"Do not click on anything for at least 6 seconds.",
"Do not click on anything for at least 10 seconds.",
"Click on the background.",
"Click on the green wide rectangle 13 times.",
"Click on the background.",
"Click on the yellow wide rectangle 12 times.",
"Click on the background.",
"Click on the green wide rectangle.",
"Do not click on anything for at least 10 seconds.",
"Click on the background.",
"Click on the blue square and then click on the orange square.",
"Click on the green wide rectangle 16 times.",
"Do not click on anything for at least 9 seconds.",
"Click on the orange square 11 times.",
"Click on the background.",
"Click on the orange square.",
"Do not click on anything for at least 9 seconds.",
"Click on the green square and then click on the green wide rectangle.",
"Do not click on anything for at least 8 seconds.",
"Click on the orange square 17 times.",
"Click on the orange wide rectangle 19 times.",
"Do not click on anything for at least 6 seconds.",
"Click on the pink square and then click on the green square.",
"Click on the blue square.",
"Click on the blue square and then click on the red wide rectangle.",
"Click on the red square.",
"Click on the red wide rectangle and then click on the yellow wide rectangle.",
"Click on the pink square 10 times.",
"Click on the blue wide rectangle 18 times.",
"Do not click on anything for at least 6 seconds.",
"Click on the blue wide rectangle.",
"Do not click on anything for at least 5 seconds.",
"Click on the red wide rectangle.",
"Do not click on anything for at least 10 seconds.",
"Click on the green square.",
"Click on the background.",
"Click on the yellow square 13 times.",
"Do not click on anything for at least 9 seconds.",
"Click on the yellow square and then click on the red wide rectangle.",
"Click on the yellow wide rectangle 12 times.",
"Click on the red square 11 times.",
"Click on the background.",
"Click on the blue wide rectangle 14 times.",
"Click on the background.",
"Click on the red wide rectangle and then click on the green wide rectangle.",
"Click on the blue square 13 times.",
"Click on the background.",
"Do not click on anything for at least 6 seconds.",
"Click on the blue wide rectangle 10 times.",
"Click on the red square.",
"Click on the background.",
"Click on the orange wide rectangle.",
"Click on the background.",
"Do not click on anything for at least 8 seconds.",
"Click on the yellow wide rectangle and then click on the blue square.",
"Do not click on anything for at least 5 seconds.",
"Click on the yellow wide rectangle.",
"Do not click on anything for at least 10 seconds.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle 12 times.",
"Click on the background.",
"Click on the yellow wide rectangle 13 times.",
"Click on the orange wide rectangle.",
"Do not click on anything for at least 6 seconds.",
"Click on the background.",
"Click on the red square.",
"Click on the background.",
"Do not click on anything for at least 6 seconds.",
"Click on the background.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle and then click on the green wide rectangle.",
"Click on the pink wide rectangle and then click on the red wide rectangle.",
"Click on the yellow wide rectangle 12 times.",
"Click on the blue square 16 times.",
"Click on the background.",
"Click on the green wide rectangle and then click on the red square.",
"Click on the red square and then click on the orange wide rectangle.",
"Click on the background.",
"Click on the red wide rectangle and then click on the green square.",
"Click on the orange square and then click on the pink square.",
"Click on the blue square 14 times.",
"Click on the orange wide rectangle 14 times.",
"Click on the blue wide rectangle.",
"Click on the red square and then click on the red wide rectangle.",
"Click on the orange square.",
"Click on the yellow square 17 times.",
"Click on the blue square and then click on the orange square.",
"Click on the pink square.",
"Click on the green wide rectangle and then click on the blue square.",
"Click on the yellow wide rectangle.",
"Do not click on anything for at least 8 seconds.",
"Do not click on anything for at least 6 seconds.",
"Click on the blue wide rectangle and then click on the orange wide rectangle.",
"Click on the yellow square and then click on the green square.",
"Click on the background.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle and then click on the blue square.",
"Click on the red wide rectangle 20 times.",
"Do not click on anything for at least 6 seconds.",
"Click on the orange wide rectangle 16 times.",
"Click on the green square and then click on the pink square.",
"Click on the yellow square and then click on the orange wide rectangle.",
"Click on the pink square and then click on the green square.",
"Click on the yellow square and then click on the red wide rectangle.",
"Click on the pink wide rectangle and then click on the blue wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the background.",
"Click on the red wide rectangle 16 times.",
"Click on the background.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle and then click on the orange wide rectangle.",
"Click on the orange square and then click on the yellow wide rectangle.",
"Click on the blue square 16 times.",
"Click on the red square 14 times.",
"Click on the pink square 18 times.",
"Do not click on anything for at least 8 seconds.",
"Click on the blue square.",
"Click on the red square.",
"Do not click on anything for at least 5 seconds.",
"Do not click on anything for at least 6 seconds.",
"Click on the red wide rectangle and then click on the green wide rectangle.",
"Click on the background.",
"Click on the yellow wide rectangle and then click on the green wide rectangle.",
"Do not click on anything for at least 7 seconds.",
"Click on the red wide rectangle.",
"Do not click on anything for at least 5 seconds.",
"Click on the background.",
"Click on the orange wide rectangle 12 times.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle and then click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle and then click on the pink wide rectangle.",
"Click on the pink wide rectangle 12 times.",
"Click on the orange square 10 times.",
"Click on the background.",
"Click on the yellow wide rectangle.",
"Click on the background.",
"Click on the red square and then click on the blue wide rectangle.",
"Click on the background. Then click on the blue wide rectangle 12 times. Then do not click on anything for at least 6 seconds. Then click on the background. Then do not click on anything for at least 7 seconds. Then click on the background. Then click on the red square 10 times. Then do not click on anything for at least 8 seconds. Then click on the background. Then do not click on anything for at least 7 seconds.",
"Click on the blue wide rectangle 19 times. Then click on the background. Then do not click on anything for at least 8 seconds. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the background. Then do not click on anything for at least 8 seconds.",
"Click on the background. Then do not click on anything for at least 7 seconds. Then click on the red wide rectangle 10 times. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the orange wide rectangle 11 times. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the green wide rectangle 13 times. Then click on the background.",
"Do not click on anything for at least 5 seconds. Then click on the orange square 10 times. Then do not click on anything for at least 5 seconds. Then click on the yellow wide rectangle 12 times. Then click on the background. Then click on the pink wide rectangle 12 times. Then do not click on anything for at least 5 seconds. Then click on the green wide rectangle 17 times. Then click on the background. Then click on the blue square 11 times.",
"Click on the background. Then click on the green wide rectangle 20 times. Then do not click on anything for at least 5 seconds. Then click on the background. Then do not click on anything for at least 8 seconds. Then click on the background.",
"Do not click on anything for at least 10 seconds. Then click on the background. Then click on the red square 11 times. Then click on the background. Then click on the yellow wide rectangle 11 times. Then click on the background. Then click on the green square 11 times. Then click on the background. Then click on the red square 20 times.",
"Do not click on anything for at least 8 seconds. Then click on the background. Then click on the blue square 12 times. Then click on the background. Then click on the blue square 10 times. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the red square 18 times. Then do not click on anything for at least 6 seconds.",
"Click on the green square 16 times. Then do not click on anything for at least 9 seconds. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the background. Then do not click on anything for at least 7 seconds. Then click on the background. Then do not click on anything for at least 6 seconds.",
"Do not click on anything for at least 10 seconds. Then click on the background. Then do not click on anything for at least 7 seconds. Then click on the background. Then click on the red square 20 times. Then click on the background. Then click on the pink square 20 times. Then do not click on anything for at least 9 seconds.",
"Click on the red square 12 times. Then do not click on anything for at least 10 seconds. Then click on the blue wide rectangle 10 times. Then do not click on anything for at least 8 seconds. Then click on the green wide rectangle 11 times. Then click on the background.",
"Click on the background. Then click on the pink wide rectangle 18 times. Then click on the background. Then click on the yellow square 19 times. Then do not click on anything for at least 10 seconds. Then click on the blue wide rectangle 18 times. Then click on the background. Then do not click on anything for at least 5 seconds.",
"Click on the yellow wide rectangle 16 times. Then do not click on anything for at least 6 seconds. Then click on the blue wide rectangle 19 times. Then do not click on anything for at least 9 seconds. Then click on the background. Then click on the green wide rectangle 16 times.",
"Do not click on anything for at least 8 seconds. Then click on the background. Then click on the blue wide rectangle 14 times. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the green square 10 times.",
"Do not click on anything for at least 5 seconds. Then click on the yellow wide rectangle 14 times. Then click on the background. Then do not click on anything for at least 7 seconds. Then click on the background. Then click on the green wide rectangle 15 times. Then click on the background. Then do not click on anything for at least 7 seconds. Then click on the background.",
"Do not click on anything for at least 9 seconds. Then click on the orange wide rectangle 14 times. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the red wide rectangle 13 times. Then click on the background.",
"Click on the background. Then click on the orange wide rectangle 19 times. Then do not click on anything for at least 5 seconds. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the blue wide rectangle 11 times. Then do not click on anything for at least 10 seconds. Then click on the background.",
"Click on the background. Then click on the green square 14 times. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the yellow square 17 times. Then click on the background. Then do not click on anything for at least 6 seconds.",
"Do not click on anything for at least 9 seconds. Then click on the background. Then click on the green wide rectangle 14 times. Then click on the background. Then click on the yellow square 19 times.",
"Do not click on anything for at least 8 seconds. Then click on the background. Then do not click on anything for at least 7 seconds. Then click on the background. Then click on the blue square 19 times. Then do not click on anything for at least 5 seconds. Then click on the red wide rectangle 20 times.",
"Do not click on anything for at least 7 seconds. Then click on the background. Then click on the pink square 19 times. Then do not click on anything for at least 7 seconds. Then click on the background. Then do not click on anything for at least 8 seconds. Then click on the background.",
"Do not click on anything for at least 6 seconds. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the background. Then click on the green wide rectangle 16 times. Then do not click on anything for at least 6 seconds. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the background.",
"Do not click on anything for at least 7 seconds. Then click on the green wide rectangle 15 times. Then do not click on anything for at least 8 seconds. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the red wide rectangle 18 times. Then do not click on anything for at least 10 seconds. Then click on the background. Then click on the pink wide rectangle 17 times. Then do not click on anything for at least 10 seconds.",
"Click on the red wide rectangle 20 times. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the orange square 17 times. Then do not click on anything for at least 9 seconds.",
"Do not click on anything for at least 5 seconds. Then click on the background. Then do not click on anything for at least 8 seconds. Then click on the background. Then click on the orange square 17 times. Then click on the background. Then click on the yellow wide rectangle 17 times. Then do not click on anything for at least 10 seconds.",
"Click on the background. Then click on the yellow square 10 times. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the yellow wide rectangle 18 times.",
"Click on the background. Then do not click on anything for at least 9 seconds. Then click on the red wide rectangle 15 times. Then click on the background. Then click on the blue wide rectangle 19 times. Then do not click on anything for at least 9 seconds. Then click on the background.",
"Click on the green square 15 times. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the yellow wide rectangle 13 times. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the background. Then click on the red wide rectangle 19 times.",
"Do not click on anything for at least 10 seconds. Then click on the background. Then click on the red wide rectangle 12 times. Then do not click on anything for at least 5 seconds. Then click on the orange wide rectangle 15 times. Then do not click on anything for at least 6 seconds. Then click on the yellow square 13 times. Then do not click on anything for at least 5 seconds.",
"Do not click on anything for at least 8 seconds. Then click on the yellow square 20 times. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the background. Then click on the red wide rectangle 17 times.",
"Do not click on anything for at least 5 seconds. Then click on the background. Then click on the orange square 13 times. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the background.",
"Click on the background. Then click on the green square 12 times. Then do not click on anything for at least 6 seconds. Then click on the blue wide rectangle 16 times. Then do not click on anything for at least 9 seconds. Then click on the red square 14 times. Then do not click on anything for at least 5 seconds. Then click on the background. Then click on the blue square 19 times. Then do not click on anything for at least 10 seconds.",
"Do not click on anything for at least 7 seconds. Then click on the background. Then click on the yellow wide rectangle 10 times. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the red wide rectangle 19 times. Then click on the background.",
"Click on the pink wide rectangle 11 times. Then do not click on anything for at least 8 seconds. Then click on the background. Then click on the red wide rectangle 11 times. Then do not click on anything for at least 9 seconds. Then click on the pink square 14 times. Then do not click on anything for at least 7 seconds.",
"Do not click on anything for at least 6 seconds. Then click on the green square 17 times. Then do not click on anything for at least 10 seconds. Then click on the background. Then click on the yellow wide rectangle 10 times. Then click on the background. Then click on the blue square 20 times. Then do not click on anything for at least 6 seconds. Then click on the green wide rectangle 14 times. Then click on the background.",
"Click on the background. Then click on the green wide rectangle 10 times. Then do not click on anything for at least 5 seconds. Then click on the orange wide rectangle 10 times. Then click on the background. Then click on the pink square 10 times. Then do not click on anything for at least 8 seconds. Then click on the red wide rectangle 20 times. Then do not click on anything for at least 10 seconds.",
"Click on the background. Then click on the green square 17 times. Then do not click on anything for at least 7 seconds. Then click on the background. Then click on the red square 15 times. Then click on the background. Then click on the red wide rectangle 13 times. Then do not click on anything for at least 10 seconds. Then click on the green square 13 times.",
"Click on the background. Then click on the orange square 14 times. Then do not click on anything for at least 6 seconds. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the background. Then click on the yellow wide rectangle 15 times.",
"Do not click on anything for at least 9 seconds. Then click on the background. Then click on the green wide rectangle 10 times. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the background.",
"Do not click on anything for at least 7 seconds. Then click on the yellow square 20 times. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the background. Then do not click on anything for at least 9 seconds.",
"Do not click on anything for at least 9 seconds. Then click on the red wide rectangle 16 times. Then do not click on anything for at least 9 seconds. Then click on the orange wide rectangle 18 times. Then click on the background. Then click on the orange square 16 times. Then do not click on anything for at least 7 seconds. Then click on the orange square 11 times.",
"Do not click on anything for at least 8 seconds. Then click on the pink wide rectangle 14 times. Then do not click on anything for at least 5 seconds. Then click on the red square 14 times. Then do not click on anything for at least 5 seconds. Then click on the blue wide rectangle 14 times. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the orange square 17 times. Then click on the background.",
"Do not click on anything for at least 9 seconds. Then click on the pink square 17 times. Then click on the background. Then click on the yellow wide rectangle 12 times. Then click on the background.",
"Click on the blue square 20 times. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the background. Then do not click on anything for at least 10 seconds. Then click on the pink square 19 times. Then do not click on anything for at least 8 seconds. Then click on the background. Then click on the pink square 15 times.",
"Click on the orange wide rectangle 10 times. Then do not click on anything for at least 7 seconds. Then click on the pink wide rectangle 20 times. Then click on the background. Then do not click on anything for at least 9 seconds. Then click on the background. Then click on the blue wide rectangle 14 times. Then click on the background. Then click on the yellow wide rectangle 10 times.",
"Click on the background. Then do not click on anything for at least 5 seconds. Then click on the background. Then click on the pink square 17 times. Then do not click on anything for at least 8 seconds. Then click on the background.",
"Do not click on anything for at least 8 seconds. Then click on the background. Then do not click on anything for at least 5 seconds. Then click on the orange square 15 times. Then click on the background. Then click on the red square 16 times. Then click on the background. Then do not click on anything for at least 8 seconds. Then click on the green wide rectangle 20 times.",
"Do not click on anything for at least 6 seconds. Then click on the background. Then click on the green square 11 times. Then click on the background. Then click on the orange wide rectangle 16 times. Then do not click on anything for at least 6 seconds.",
"Do not click on anything for at least 5 seconds. Then click on the red square 10 times. Then do not click on anything for at least 9 seconds. Then click on the background. Then click on the blue wide rectangle 14 times. Then do not click on anything for at least 9 seconds.",
"Click on the background. Then click on the red square 17 times. Then do not click on anything for at least 5 seconds. Then click on the background. Then do not click on anything for at least 6 seconds. Then click on the orange square 17 times. Then do not click on anything for at least 8 seconds. Then click on the background. Then click on the red wide rectangle 15 times. Then click on the background.",
]

y = [74,179,278]
x = [70,170,275,482]
pos = {"red":[6,9], "yellow":[1,10],"green":[4,11],"orange":[3,8],"blue":[5,7],"pink":[0,2]}

ti = 0
bx = 126 
by = 49 
ti = 1466253110.28

col = ["red","green","blue","yellow","orange","pink"]
e = 47
def h():
    global e
    a = range(6)
    for b in range(1, 6):
        e *= 53
        e %= 1000000009
        k = e % (b+1)
        d = a[b]
        a[b] = a[k]
        a[k] = d
    return a

def l():
    f = h()
    g = h()
    for i in range(6):
        x = i / 3
        y = i % 3
        pos[col[f[i]]][0] = x * 3 + y
    for i in range(6):
        x = 2 + i / 3
        y = i % 3
        pos[col[g[i]]][1] = x * 3 + y

color_in = [[0 for i in range(10)] for i in range(10)]
def print_color():
    for co in col:
        color_in[pos[co][0]%3][pos[co][0]/3] = co[0]
    for co in col:
        color_in[pos[co][1]%3][pos[co][1]/3] = co[0]
        #print pos['pink'][1]
    for i in xrange(3):
        for j in xrange(4):
            print color_in[i][j],
        print

def go(move):
    global ti
    if "not" in move:
        ti += 30.0
    elif "background" in move:
        print bx, by, ti
        ti += 1
    else:
        co = '-1'
        for c in pos:
            if c in move:
                co = c
        px = -1
        py = -1
        if "wide" in move:
            px = pos[co][1]/3
            py = pos[co][1]%3
        else:
            px = pos[co][0]/3
            py = pos[co][0]%3

        times = 1
        for t in move.split():
            if t.isdigit():
                times = int(t)
        for i in xrange(times):
            print x[px], y[py],ti
            ti += 1

sys.stdout= open("d2.out","w")
print bx,by,ti
ti += 1
l()
#print_color()
t = 0 
for move in moves:
    print "next", ti
    t+=1
    if t!=1:
        l()
    #print_color()
    for mo in move.split("hen"):
        go(mo)
print "done", ti

      

